In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Introduction to Tensors
### Creating tensors

Pytorch tensors are created using 'torch.Tensor()'

In [2]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
scalar.shape

torch.Size([])

In [6]:
# Vcctor

vector = torch.tensor([7,7,8])
vector

tensor([7, 7, 8])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([3])

In [9]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,7]])
MATRIX

tensor([[7, 8],
        [9, 7]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
print(f"Shape of Scalar: {scalar.shape}, Ndim of Scalar: {scalar.ndim} ")
print(f"Shape of Vector: {vector.shape}, Ndim of Vector: {vector.ndim} ")
print(f"Shape of Matrix: {MATRIX.shape}, Ndim of Scalar: {MATRIX.ndim} ")

Shape of Scalar: torch.Size([]), Ndim of Scalar: 0 
Shape of Vector: torch.Size([3]), Ndim of Vector: 1 
Shape of Matrix: torch.Size([2, 2]), Ndim of Scalar: 2 


In [14]:
# Tensor

TENSOR = torch.tensor([[[1, 2, 3], 
                        [4, 5, 6],
                        [9, 2, 3]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [9, 2, 3]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
print(f"Shape of Tensor: {TENSOR.shape}, Ndim of Scalar: {TENSOR.ndim} ")

Shape of Tensor: torch.Size([1, 3, 3]), Ndim of Scalar: 3 


In [18]:
my_tensor = torch.tensor([[[9,8,7],
              [1,2,3]]])

my_tensor

tensor([[[9, 8, 7],
         [1, 2, 3]]])

In [19]:
my_tensor.shape

torch.Size([1, 2, 3])

### Random tensors

In [20]:
# Create a random tensor of shape (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3902, 0.2621, 0.9441, 0.9081],
        [0.6234, 0.7468, 0.2877, 0.1393],
        [0.7009, 0.2908, 0.9176, 0.9696]])

In [21]:
random_tensor.shape

torch.Size([3, 4])

In [22]:
random_tensor.ndim

2

In [23]:
# Create a random tensor similar shape to an image

random_image_size_tensor = torch.rand(size=(3,224,224)) # Height, Width, Color
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zero and Ones

In [24]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(3,4))

zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
# Create a tensor of all ones

ones = torch.ones(size=(3,4))

ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [27]:
# Use torch.range()

one_to_ten = torch.arange(start = 0 , end = 1000 , step = 11)
one_to_ten


one_to_ten = torch.arange(0 ,11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# Creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [29]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # What datatype tensor is
                               device=None, # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients

float_32_tensor.dtype

torch.float32

In [30]:
print(float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device)

torch.Size([3]) torch.float32 cpu


In [31]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [32]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

In [33]:
# Create tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9563, 0.4319, 0.3473, 0.6794],
        [0.4698, 0.4928, 0.4420, 0.8187],
        [0.1530, 0.0494, 0.4715, 0.7423]])

In [34]:
# Find out details

print(some_tensor)
print(f"Data Type of tensor: {some_tensor.dtype}")
print(f"Shape of Tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.9563, 0.4319, 0.3473, 0.6794],
        [0.4698, 0.4928, 0.4420, 0.8187],
        [0.1530, 0.0494, 0.4715, 0.7423]])
Data Type of tensor: torch.float32
Shape of Tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors

Tensor operations include:
* Addition
* Substaction
* Multiplication (elemet-wise)
* Division 
* Matrix multiplication

In [35]:
# Find out details

print(some_tensor)
print(f"Data Type of tensor: {some_tensor.dtype}")
print(f"Shape of Tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.9563, 0.4319, 0.3473, 0.6794],
        [0.4698, 0.4928, 0.4420, 0.8187],
        [0.1530, 0.0494, 0.4715, 0.7423]])
Data Type of tensor: torch.float32
Shape of Tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [36]:
# Create a tensor and addition

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [37]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [38]:
# Substract 10

tensor - 10

tensor([-9, -8, -7])

In [39]:
# Try out PyTorch inbuilt functions

torch.mul(tensor, 10)

tensor([10, 20, 30])

In [40]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

In [41]:
# Element wise mul

tensor

tensor([1, 2, 3])

In [42]:
print(tensor, "*" ,tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [43]:
# Matrix multiplication

torch.matmul(tensor,tensor)

tensor(14)

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
- (3, 2) @ (3, 2) won't work
- (2, 3) @ (2, 3) will work
- (3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the **outer dimensions**:
* (2, 3) @ (2, 3) -> (2i2)

In [44]:
torch.matmul(torch.rand(3,2), torch.rand(3,2))


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [45]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))


tensor([[0.4203, 0.1087, 0.3630],
        [0.4228, 0.1062, 0.3917],
        [0.6962, 0.1770, 0.6260]])

In [46]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,8,9],
                         [10,11,12]])

result = torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul()
print(f"Tensor A Shape: {tensor_A.shape} @ Tensor B Shape: {tensor_B.shape} \n  {result}")



Tensor A Shape: torch.Size([3, 2]) @ Tensor B Shape: torch.Size([2, 3]) 
  tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [47]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axis or dimensions of a given tensor

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor

x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x)

tensor(450)

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
print(f"Maksimum değer: {torch.max(x)}, Maksimum değer indexi: {torch.argmax(x)}")

Maksimum değer: 90, Maksimum değer indexi: 9


In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in tensor that has min value with argmin() -> returns index position
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensons from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted in a certain way

In [ ]:
# Let's crate a tensor

import torch

x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension

x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x = torch.arange(1.,10.)
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x_reshaped = x.reshape(9, 1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
x = torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1) 
x_stacked

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [ ]:
z = x.view(5,2)
z, z.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [ ]:
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.],
         [ 5.,  4.],
         [ 5.,  6.],
         [ 5.,  8.],
         [ 5., 10.]]),
 tensor([ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.]))

In [ ]:
x_reshaped = x.reshape(5, 3)
x_reshaped

RuntimeError: shape '[5, 3]' is invalid for input of size 10

In [ ]:
# Change the view
x = torch.arange(1.,10.)
x_reshaped = x.reshape(1, 9)

z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x because a view of a tensor shares the same memory as the original

z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous Tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")


Previous Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - add a single dimension to a tager tensor
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsquuzed = x_squeezed.unsqueeze(dim=0)

print(f"\nNew Tensor: {x_unsquuzed}")
print(f"Previous shape: {x_unsquuzed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])


In [48]:
# torch.permute - rearranges the dimensions of a tagert tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #height, width, color_channel

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")



Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [49]:
x_permuted[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing


In [52]:
# Create a tensor

import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [53]:
# Let's index
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [54]:
x[0][0]

tensor([1, 2, 3])

In [55]:
x[0][0][0]

tensor(1)

In [56]:
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [57]:
x[:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [58]:
x[:,:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension

x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2n dimension

x[:, 1, 1]

tensor([5])

In [ ]:
# Get index of 0 of the 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

## Pytorch tensors & Numpy

In [ ]:
# Numpy array to tensor

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
 # Tensor to Numpy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In [ ]:
import torch

# Create two random tensors

random_tensor_A = torch.rand(3,4)

random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6841, 0.5803, 0.2209, 0.7133],
        [0.6158, 0.5864, 0.2273, 0.7744],
        [0.3405, 0.2858, 0.7062, 0.3121]])
tensor([[0.1743, 0.0389, 0.4262, 0.0543],
        [0.8561, 0.1782, 0.7863, 0.6708],
        [0.2405, 0.1565, 0.3962, 0.3698]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors

import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and Pytorch objects on GPU


In [ ]:
import torch

torch.cuda.is_available()

True

In [59]:
# Setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

## Putting tensors on the GPU

In [60]:
# Create a tensor (default on cpu)

tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [61]:
# Move tensor to GPU

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [62]:
tensor_back_on_cpu = tensor_on_gpu.cpu()

In [63]:
print(tensor_back_on_cpu, tensor_back_on_cpu.device)

tensor([1, 2, 3]) cpu


### Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

# Exercises

In [ ]:
# Create a random tensor with shape (7, 7)

tensor_1 = torch.rand(size=(7,7))
tensor_1, tensor_1.shape

(tensor([[0.2219, 0.3570, 0.2956, 0.7059, 0.6671, 0.0369, 0.1941],
         [0.1123, 0.3594, 0.0603, 0.6973, 0.9664, 0.3479, 0.9951],
         [0.8741, 0.8747, 0.1449, 0.1749, 0.6003, 0.2361, 0.0990],
         [0.4098, 0.5389, 0.6940, 0.5426, 0.6446, 0.0907, 0.9713],
         [0.3037, 0.6275, 0.9274, 0.9483, 0.9049, 0.2860, 0.7159],
         [0.6850, 0.9240, 0.6270, 0.3166, 0.1771, 0.4601, 0.8625],
         [0.4725, 0.1089, 0.2056, 0.9702, 0.4940, 0.6340, 0.5722]]),
 torch.Size([7, 7]))

In [ ]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7
tensor_2 = torch.rand(size=(1,7))

torch.mm(tensor_1,tensor_2.T)

tensor([[1.3116],
        [2.0304],
        [1.7134],
        [2.2374],
        [2.6844],
        [2.3593],
        [1.6030]])

In [ ]:
# Set the random seed to 0 and do exercises 2 & 3 over again.
